import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Form from '@/components/form/Form'
import TableFakeStore from '@/components/tableFakeStore/TableFakeStore'
import DeleteOneLetter from '@/components/deleteOneLetter/DeleteOneLetter'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>

        <TableFakeStore></TableFakeStore>

        <Form></Form>

        <DeleteOneLetter></DeleteOneLetter>
      </main>
    </>
  )
}
